<?php

$exchangeItems = [
    4564 => [
        120,
        "Antidote",
        "1st tab",
        "Materiel",
    ],
    4568 => [
        290,
        "Echo Drops",
        "1st tab",
        "Materiel",
    ],
    5594 => [
        12,
        "Grade 1 Dark Matter",
        "1st tab",
        "Materiel",
    ],
    5595 => [
        34,
        "Grade 2 Dark Matter",
        "1st tab",
        "Materiel",
    ],
    5596 => [
        70,
        "Grade 3 Dark Matter",
        "1st tab",
        "Materiel",
    ],
    15855 => [
        500,
        "Althyk Lavender Seeds",
        "1st tab",
        "Materiel",
    ],
    15856 => [
        500,
        "Voidrake Seeds",
        "1st tab",
        "Materiel",
    ],
    4567 => [
        1710,
        "Smelling Salts",
        "1st tab",
        "Materiel",
    ],
    4568 => [
        1010,
        "Spine Drops",
        "1st tab",
        "Materiel",
    ],
    5597 => [
        138,
        "Grade 4 Dark Matter",
        "1st tab",
        "Materiel",
    ],
    5598 => [
        230,
        "Grade 5 Dark Matter",
        "1st tab",
        "Materiel",
    ],
    5357 => [
        200,
        "Swan Feather",
        "1st tab",
        "Materials",
    ],
    5358 => [
        200,
        "Eagle Feather",
        "1st tab",
        "Materials",
    ],
    5558 => [
        200,
        "Pudding Flesh",
        "1st tab",
        "Materials",
    ],
    6141 => [
        500,
        "Cordial",
        "2nd tab",
        "Materiel",
    ],
    7059 => [
        1500,
        "Spiritbond Potion",
        "2nd tab",
        "Materiel",
    ],
    7621 => [
        200,
        "Glamour Dispeller",
        "2nd tab",
        "Materiel",
    ],
    21800 => [
        200,
        "Glamour Prism",
        "2nd tab",
        "Materiel",
    ],
    10386 => [
        345,
        "Grade 6 Dark Matter",
        "3rd tab",
        "Materiel",
    ],
    17837 => [
        575,
        "Grade 7 Dark Matter",
        "3rd tab",
        "Materiel",
    ],
    4715 => [
        500,
        "Trapper's Quiche",
        "3rd tab",
        "Materiel",
    ],
    4720 => [
        500,
        "Fish Soup",
        "3rd tab",
        "Materiel",
    ],
    12844 => [
        900,
        "Hot Chocolate",
        "3rd tab",
        "Materiel",
    ],
    12847 => [
        700,
        "Marron Glace",
        "3rd tab",
        "Materiel",
    ],
    12849 => [
        550,
        "Kaiser Roll",
        "3rd tab",
        "Materiel",
    ],
    12854 => [
        800,
        "Morel Salad",
        "3rd tab",
        "Materiel",
    ],
    12858 => [
        600,
        "Cockatrice Meatballs",
        "3rd tab",
        "Materiel",
    ],
    13743 => [
        550,
        "Sesame Cookie",
        "3rd tab",
        "Materiel",
    ],
    13595 => [
        5000,
        "Kingcake",
        "3rd tab",
        "Materiel",
    ],
    13591 => [
        5000,
        "Titanium Alloy Mirror",
        "3rd tab",
        "Materiel",
    ],
    13589 => [
        5000,
        "Adamantite Francesca",
        "3rd tab",
        "Materiel",
    ],
    13593 => [
        5000,
        "Dispelling Arrow",
        "3rd tab",
        "Materiel",
    ],
    15649 => [
        7000,
        "Glass Fiber",
        "3rd tab",
        "Materials",
    ],
    9356 => [
        2300,
        "Quick-hardening Sealant",
        "3rd tab",
        "Materials",
    ],
    9371 => [
        250,
        "Smoked Bacon",
        "3rd tab",
        "Materials",
    ],
    9372 => [
        250,
        "Roasted Coffee Beans",
        "3rd tab",
        "Materials",
    ],
    9368 => [
        2250,
        "Wootz Ore",
        "3rd tab",
        "Materials",
    ],
    9367 => [
        2250,
        "Arachne Web",
        "3rd tab",
        "Materials",
    ],
    9369 => [
        250,
        "Raziqsap",
        "3rd tab",
        "Materials",
    ],
    9370 => [
        2250,
        "Dubbin",
        "3rd tab",
        "Materials",
    ],
    9366 => [
        250,
        "Borax",
        "3rd tab",
        "Materials",
    ],
    7605 => [
        30,
        "Canard Breast",
        "3rd tab",
        "Materials",
    ],
    7603 => [
        30,
        "Dalamud Popoto",
        "3rd tab",
        "Materials",
    ],
    7604 => [
        30,
        "Royal Kukuru Bean",
        "3rd tab",
        "Materials",
    ],
    7602 => [
        30,
        "Star Anise",
        "3rd tab",
        "Materials",
    ],
    7597 => [
        1500,
        "Scheelite",
        "3rd tab",
        "Materials",
    ],
    7601 => [
        1500,
        "Emery",
        "3rd tab",
        "Materials",
    ],
    7596 => [
        1500,
        "Petrified Log",
        "3rd tab",
        "Materials",
    ],
    7600 => [
        1500,
        "Cashmere Fleece",
        "3rd tab",
        "Materials",
    ],
    7599 => [
        1500,
        "Saurian Skin",
        "3rd tab",
        "Materials",
    ],
    7806 => [
        450,
        "Tawny Latex",
        "3rd tab",
        "Materials",
    ],
    7598 => [
        1500,
        "Raziqsand",
        "3rd tab",
        "Materials",
    ],
    6151 => [
        20,
        "Cooking Sherry",
        "3rd tab",
        "Materials",
    ],
    5119 => [
        200,
        "Peacock Ore",
        "3rd tab",
        "Materials",
    ],
    5261 => [
        200,
        "Aqueous Whetstone",
        "3rd tab",
        "Materials",
    ],
    5274 => [
        200,
        "Minium",
        "3rd tab",
        "Materials",
    ],
    5501 => [
        200,
        "Potash",
        "3rd tab",
        "Materials",
    ],
    5502 => [
        200,
        "Lime Sulphur",
        "3rd tab",
        "Materials",
    ],
    6153 => [
        20,
        "Filtered Water",
        "3rd tab",
        "Materials",
    ],
    6154 => [
        20,
        "Voidsent Blood",
        "3rd tab",
        "Materials",
    ],
    5531 => [
        200,
        "Animal Fat",
        "3rd tab",
        "Materials",
    ],
    5532 => [
        200,
        "Hardened Sap",
        "3rd tab",
        "Materials",
    ],
    5530 => [
        200,
        "Coke",
        "3rd tab",
        "Materials",
    ]
];

?>